#lang racket
(display "--------Задание 1--------\n")
(display "Вычисление объема куба\n")
(display "Введите длину ребра(см) и нажмите клавижу <Enter>\n")
(define a(read))
(define (cube x)
  (*(* x x) x))
(display (format "Объем куба: ~a куб.см" (cube a)))

(display "\n--------Задание 2--------\n")
(display "Вычисление объема цилиндра.\n")
(display "Введите исходные данные:\n")
(display "радиус основания (см)\n")
(define r(read))
(display "высота цилиндра (см)\n")
(define h(read))
(define pi 3.14)
(display (format "Объем цилиндра ~a см. куб." (*(* pi (* r r))h)))

(display "\n--------Задание 4--------\n")
(display "Вычисление стоимости покупки\n")
(display "Введите исходные данные:\n")
(display "Цена одного килограмма яблок (руб./кг)\n")
(define cena(read))
(display "Вес яблок (кг)\n")
(define ves(read))
(display (format "Стоимость покупки: ~a руб."(* cena ves)))
