#lang racket
(display "--------Задание 1--------\n")
(display "Вычисление площади кольца\n")
(display "Введите исходные данные:\n")
(display "Радиус кольца (см)\n")
(define rr(read))
(display "Радиус отверстия (см)\n")
(define rh(read))
(define pi 3.14)
(define (area x y)
  (* (- (* x x) (* y y)) pi))
(display (if (< rh rr)
             (format "Объем куба: ~a куб.см" (area rr rh))
             "Ошибка! Радиус отверстия не может быть больше радиуса кольца."))

(display "\n--------Задание 3--------\n")
(display "Введите год:\n")
(define year(read))
(display (if (= (remainder year 4) 0)
             (format "~a год - високосный." year)
             (format "~a год - не високосный." year)))

(display "\n--------Задание 7--------\n")
(display "В каком году началась вторая мировая война?\n")
(display "Введите число и нажмите <Enter>\n")
(define war(read))
(display (if (= war 1939)
             "Правильно!"
             "Не правильно. Вторая мировая война началась в 1939 г."))
